# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chess.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from functools import partial
import chess


class Ui_Chess(object):

    # Importing all the functions from other modules
    from src.MakeMove import makeMove
    from src.Set import setTheIcon
    from src.Set import setTheIconForBlack
    from src.Set import setTheIconForWhite
    from src.Get import getTheIcon
    from src.Get import getTheSquare

    # universal variables
    board = chess.Board()
    btnBoard = []
    whitePieces = []
    blackPieces = []
    pieceSelected = False
    legalMoves = []
    selectedPiece = ""
    turnOfWhite = True
    whiteOut = 0
    blackOut = 0
    rookBIconLink = "images/rookB.png"
    rookWIconLink = "images/rookW.png"
    knightBIconLink = "images/knightB.png"
    knightWIconLink = "images/knightW.png"
    bishopBIconLink = "images/bishopB.png"
    bishopWIconLink = "images/bishopW.png"
    kingBIconLink = "images/kingB.png"
    kingWIconLink = "images/kingW.png"
    queenBIconLink = "images/queenB.png"
    queenWIconLink = "images/queenW.png"
    pawnBIconLink = "images/pawnB.png"
    pawnWIconLink = "images/pawnW.png"

    


    def setupUi(self, Chess):
        Chess.setObjectName("Chess")
        Chess.resize(1076, 687)
        Chess.setMaximumSize(1076, 687)
        Chess.setAutoFillBackground(False)
        Chess.setStyleSheet("background: rgb(31, 31, 31);")
        self.centralwidget = QtWidgets.QWidget(Chess)
        self.centralwidget.setObjectName("centralwidget")
        self.sidePanel = QtWidgets.QFrame(self.centralwidget)
        self.sidePanel.setGeometry(QtCore.QRect(698, 6, 373, 677))
        self.sidePanel.setStyleSheet("background: rgb(70, 70, 70);")
        self.sidePanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sidePanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sidePanel.setObjectName("sidePanel")
        self.layoutWidget = QtWidgets.QWidget(self.sidePanel)
        self.layoutWidget.setGeometry(QtCore.QRect(4, 2, 364, 88))
        self.layoutWidget.setObjectName("layoutWidget")
        self.botOutPieces = QtWidgets.QGridLayout(self.layoutWidget)
        self.botOutPieces.setContentsMargins(0, 0, 0, 0)
        self.botOutPieces.setHorizontalSpacing(2)
        self.botOutPieces.setVerticalSpacing(0)
        self.botOutPieces.setObjectName("botOutPieces")

        for i in range(1,-1,-1):
            blackPiecesRow = []
            for j in range(8):
                botBtn = QtWidgets.QPushButton(self.layoutWidget)
                botBtn.setStyleSheet("background: white;\n"
                    "color: black;\n"
                    "height: 30px;\n"
                    "width: 30px;\n"
                    "icon-size: 30px;\n"
                    "")
                botBtn.setText("")
                botBtn.setObjectName("bot"+str((1-i)*8+j+1))
                self.botOutPieces.addWidget(botBtn, i, j, 1, 1)
                blackPiecesRow.append(botBtn)
            self.blackPieces.append(blackPiecesRow)


        self.humanIcon = QtWidgets.QLabel(self.sidePanel)
        self.humanIcon.setGeometry(QtCore.QRect(20, 484, 71, 73))
        self.humanIcon.setStyleSheet("font-size: 40px;\n"
"color: white;\n"
"background: rgb(51, 51, 51);")
        self.humanIcon.setText("")
        self.humanIcon.setPixmap(QtGui.QPixmap("images/userW.png"))
        self.humanIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.humanIcon.setObjectName("humanIcon")
        self.botIcon = QtWidgets.QLabel(self.sidePanel)
        self.botIcon.setGeometry(QtCore.QRect(20, 120, 71, 73))
        self.botIcon.setStyleSheet("font-size: 40px;\n"
"color: white;\n"
"background: rgb(204, 204, 204)")
        self.botIcon.setText("")
        self.botIcon.setPixmap(QtGui.QPixmap("images/botB.png"))
        self.botIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.botIcon.setObjectName("botIcon")
        self.botScore = QtWidgets.QLabel(self.sidePanel)
        self.botScore.setGeometry(QtCore.QRect(108, 124, 103, 61))
        self.botScore.setStyleSheet("color: rgb(51, 51, 51);\n"
"font-size: 40px;\n"
"background: rgb(204, 204, 204);")
        self.botScore.setAlignment(QtCore.Qt.AlignCenter)
        self.botScore.setObjectName("botScore")
        self.humanScore = QtWidgets.QLabel(self.sidePanel)
        self.humanScore.setGeometry(QtCore.QRect(108, 490, 103, 61))
        self.humanScore.setStyleSheet("color: rgb(204, 204, 204);\n"
"font-size: 40px;\n"
"background: rgb(51, 51, 51);")
        self.humanScore.setAlignment(QtCore.Qt.AlignCenter)
        self.humanScore.setObjectName("humanScore")
        self.humanTimer = QtWidgets.QLabel(self.sidePanel)
        self.humanTimer.setGeometry(QtCore.QRect(224, 490, 141, 61))
        self.humanTimer.setStyleSheet("color: rgb(204, 204, 204);\n"
"font-size: 40px;\n"
"background: rgb(51, 51, 51);")
        self.humanTimer.setAlignment(QtCore.Qt.AlignCenter)
        self.humanTimer.setObjectName("humanTimer")
        self.botTimer = QtWidgets.QLabel(self.sidePanel)
        self.botTimer.setGeometry(QtCore.QRect(224, 124, 141, 61))
        self.botTimer.setStyleSheet("color: rgb(51, 51, 51);\n"
"font-size: 40px;\n"
"background: rgb(204, 204, 204);")
        self.botTimer.setAlignment(QtCore.Qt.AlignCenter)
        self.botTimer.setObjectName("botTimer")
        self.botLabel = QtWidgets.QLabel(self.sidePanel)
        self.botLabel.setGeometry(QtCore.QRect(26, 98, 49, 16))
        self.botLabel.setStyleSheet("color: white;\n"
"font-size: 16px;")
        self.botLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.botLabel.setObjectName("botLabel")
        self.humanLabel = QtWidgets.QLabel(self.sidePanel)
        self.humanLabel.setGeometry(QtCore.QRect(26, 560, 59, 16))
        self.humanLabel.setStyleSheet("color: white;\n"
"font-size: 16px;")
        self.humanLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.humanLabel.setObjectName("humanLabel")
        self.botScoreLabel = QtWidgets.QLabel(self.sidePanel)
        self.botScoreLabel.setGeometry(QtCore.QRect(116, 98, 49, 16))
        self.botScoreLabel.setStyleSheet("color: white;\n"
"font-size: 16px;")
        self.botScoreLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.botScoreLabel.setObjectName("botScoreLabel")
        self.humanScoreLabel = QtWidgets.QLabel(self.sidePanel)
        self.humanScoreLabel.setGeometry(QtCore.QRect(116, 560, 49, 16))
        self.humanScoreLabel.setStyleSheet("color: white;\n"
"font-size: 16px;")
        self.humanScoreLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.humanScoreLabel.setObjectName("humanScoreLabel")
        self.botTimerLabel = QtWidgets.QLabel(self.sidePanel)
        self.botTimerLabel.setGeometry(QtCore.QRect(232, 98, 49, 16))
        self.botTimerLabel.setStyleSheet("color: white;\n"
"font-size: 16px;")
        self.botTimerLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.botTimerLabel.setObjectName("botTimerLabel")
        self.humanTimerLabel = QtWidgets.QLabel(self.sidePanel)
        self.humanTimerLabel.setGeometry(QtCore.QRect(232, 560, 49, 16))
        self.humanTimerLabel.setStyleSheet("color: white;\n"
"font-size: 16px;")
        self.humanTimerLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.humanTimerLabel.setObjectName("humanTimerLabel")
        self.layoutWidget1 = QtWidgets.QWidget(self.sidePanel)
        self.layoutWidget1.setGeometry(QtCore.QRect(4, 588, 364, 88))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.humanOutPieces = QtWidgets.QGridLayout(self.layoutWidget1)
        self.humanOutPieces.setContentsMargins(0, 0, 0, 0)
        self.humanOutPieces.setHorizontalSpacing(2)
        self.humanOutPieces.setVerticalSpacing(0)
        self.humanOutPieces.setObjectName("humanOutPieces")
        for i in range(2):
            whitePiecesRow = []
            for j in range(8):
                humanBtn = QtWidgets.QPushButton(self.layoutWidget1)
                humanBtn.setStyleSheet("background: rgb(118, 150, 86);\n"
                    "color: white;\n"
                    "height: 30px;\n"
                    "width: 30px;\n"
                    "icon-size: 30px;\n"
                    "")
                humanBtn.setText("")
                humanBtn.setObjectName("human"+str(i*8+j+1))
                self.humanOutPieces.addWidget(humanBtn, i, j, 1, 1)
                whitePiecesRow.append(humanBtn)
            self.whitePieces.append(whitePiecesRow)
        
        self.chessIconKing = QtWidgets.QLabel(self.sidePanel)
        self.chessIconKing.setGeometry(QtCore.QRect(148, 292, 71, 73))
        self.chessIconKing.setStyleSheet("color: white;\n"
"background: none;")
        self.chessIconKing.setText("")
        self.chessIconKing.setPixmap(QtGui.QPixmap("images/kingW.png"))
        self.chessIconKing.setAlignment(QtCore.Qt.AlignCenter)
        self.chessIconKing.setObjectName("chessIconKing")
        self.chessIconQueen = QtWidgets.QLabel(self.sidePanel)
        self.chessIconQueen.setGeometry(QtCore.QRect(186, 282, 71, 73))
        self.chessIconQueen.setStyleSheet("color: white;\n"
"background: none;")
        self.chessIconQueen.setText("")
        self.chessIconQueen.setPixmap(QtGui.QPixmap("images/queenW.png"))
        self.chessIconQueen.setAlignment(QtCore.Qt.AlignCenter)
        self.chessIconQueen.setObjectName("chessIconQueen")
        self.chessIconBishop = QtWidgets.QLabel(self.sidePanel)
        self.chessIconBishop.setGeometry(QtCore.QRect(110, 282, 71, 73))
        self.chessIconBishop.setStyleSheet("color: white;\n"
"background: none;")
        self.chessIconBishop.setText("")
        self.chessIconBishop.setPixmap(QtGui.QPixmap("images/bishopW.png"))
        self.chessIconBishop.setAlignment(QtCore.Qt.AlignCenter)
        self.chessIconBishop.setObjectName("chessIconBishop")
        self.chessIconRook = QtWidgets.QLabel(self.sidePanel)
        self.chessIconRook.setGeometry(QtCore.QRect(72, 272, 71, 73))
        self.chessIconRook.setStyleSheet("color: white;\n"
"background: none;")
        self.chessIconRook.setText("")
        self.chessIconRook.setPixmap(QtGui.QPixmap("images/rookW.png"))
        self.chessIconRook.setAlignment(QtCore.Qt.AlignCenter)
        self.chessIconRook.setObjectName("chessIconRook")
        self.chessIconKnight = QtWidgets.QLabel(self.sidePanel)
        self.chessIconKnight.setGeometry(QtCore.QRect(224, 272, 71, 73))
        self.chessIconKnight.setStyleSheet("color: white;\n"
"background: none;")
        self.chessIconKnight.setText("")
        self.chessIconKnight.setPixmap(QtGui.QPixmap("images/knightW.png"))
        self.chessIconKnight.setAlignment(QtCore.Qt.AlignCenter)
        self.chessIconKnight.setObjectName("chessIconKnight")
        self.chessIconPawn = QtWidgets.QLabel(self.sidePanel)
        self.chessIconPawn.setGeometry(QtCore.QRect(262, 262, 71, 73))
        self.chessIconPawn.setStyleSheet("color: white;\n"
"background: none;")
        self.chessIconPawn.setText("")
        self.chessIconPawn.setPixmap(QtGui.QPixmap("images/pawnW.png"))
        self.chessIconPawn.setAlignment(QtCore.Qt.AlignCenter)
        self.chessIconPawn.setObjectName("chessIconPawn")
        self.chessIconPawn2 = QtWidgets.QLabel(self.sidePanel)
        self.chessIconPawn2.setGeometry(QtCore.QRect(34, 262, 71, 73))
        self.chessIconPawn2.setStyleSheet("color: white;\n"
"background: none;\n"
"")
        self.chessIconPawn2.setText("")
        self.chessIconPawn2.setPixmap(QtGui.QPixmap("images/pawnW.png"))
        self.chessIconPawn2.setAlignment(QtCore.Qt.AlignCenter)
        self.chessIconPawn2.setObjectName("chessIconPawn2")
        self.chessIconText = QtWidgets.QLabel(self.sidePanel)
        self.chessIconText.setGeometry(QtCore.QRect(74, 344, 213, 75))
        self.chessIconText.setStyleSheet("color: white;\n"
"font-size: 46px;\n"
"background: none;")
        self.chessIconText.setAlignment(QtCore.Qt.AlignCenter)
        self.chessIconText.setObjectName("chessIconText")
        self.chessIconQueen.raise_()
        self.layoutWidget.raise_()
        self.humanIcon.raise_()
        self.botIcon.raise_()
        self.botScore.raise_()
        self.humanScore.raise_()
        self.humanTimer.raise_()
        self.botTimer.raise_()
        self.botLabel.raise_()
        self.humanLabel.raise_()
        self.botScoreLabel.raise_()
        self.humanScoreLabel.raise_()
        self.botTimerLabel.raise_()
        self.humanTimerLabel.raise_()
        self.layoutWidget.raise_()
        self.chessIconKing.raise_()
        self.chessIconBishop.raise_()
        self.chessIconRook.raise_()
        self.chessIconPawn.raise_()
        self.chessIconPawn2.raise_()
        self.chessIconKnight.raise_()
        self.chessIconText.raise_()
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setGeometry(QtCore.QRect(5, 6, 687, 677))
        self.mainFrame.setStyleSheet("background: rgb(70, 70, 70);")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.layoutWidget_2 = QtWidgets.QWidget(self.mainFrame)
        self.layoutWidget_2.setGeometry(QtCore.QRect(38, 0, 644, 644))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.chessBoard = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.chessBoard.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.chessBoard.setContentsMargins(0, 0, 0, 0)
        self.chessBoard.setHorizontalSpacing(6)
        self.chessBoard.setVerticalSpacing(0)
        self.chessBoard.setObjectName("chessBoard")
        
        for i in range(8):
            btnRow = []
            for j in range(8):
                btn = QtWidgets.QPushButton(self.layoutWidget_2)
                if((i+j)%2 == 0):
                    btn.setStyleSheet("background: rgb(118, 150, 86);\n"
                        "color: white;\n"
                        "height: 65px;\n"
                        "width: 65px;\n"
                        "icon-size: 65px;\n"
                        "")
                else:
                    btn.setStyleSheet("background: white;\n"
                    "color: black;\n"
                    "height: 65px;\n"
                    "width: 65px;\n"
                    "icon-size: 65px;\n"
                    "")
                btn.setText("")
                btn.setObjectName(str(8 - i)+chr(97 + j))
                btnRow.append(btn)
                # self.chessBoard.addWidget(self.pos[i][j], i, j, 1, 1)
            self.btnBoard.append(btnRow)
        
        self.setTheIcon(0, 0, self.rookBIconLink)
        self.setTheIcon(0, 7, self.rookBIconLink)
        self.setTheIcon(0, 1, self.knightBIconLink)
        self.setTheIcon(0, 6, self.knightBIconLink)
        self.setTheIcon(0, 2, self.bishopBIconLink)
        self.setTheIcon(0, 5, self.bishopBIconLink)
        self.setTheIcon(0, 3, self.queenBIconLink)
        self.setTheIcon(0, 4, self.kingBIconLink)
        self.setTheIcon(1, 0, self.pawnBIconLink)
        self.setTheIcon(1, 1, self.pawnBIconLink)
        self.setTheIcon(1, 2, self.pawnBIconLink)
        self.setTheIcon(1, 3, self.pawnBIconLink)
        self.setTheIcon(1, 4, self.pawnBIconLink)
        self.setTheIcon(1, 5, self.pawnBIconLink)
        self.setTheIcon(1, 6, self.pawnBIconLink)
        self.setTheIcon(1, 7, self.pawnBIconLink)
        self.setTheIcon(7, 0, self.rookWIconLink)
        self.setTheIcon(7, 7, self.rookWIconLink)
        self.setTheIcon(7, 1, self.knightWIconLink)
        self.setTheIcon(7, 6, self.knightWIconLink)
        self.setTheIcon(7, 2, self.bishopWIconLink)
        self.setTheIcon(7, 5, self.bishopWIconLink)
        self.setTheIcon(7, 3, self.queenWIconLink)
        self.setTheIcon(7, 4, self.kingWIconLink)
        self.setTheIcon(6, 0, self.pawnWIconLink)
        self.setTheIcon(6, 1, self.pawnWIconLink)
        self.setTheIcon(6, 2, self.pawnWIconLink)
        self.setTheIcon(6, 3, self.pawnWIconLink)
        self.setTheIcon(6, 4, self.pawnWIconLink)
        self.setTheIcon(6, 5, self.pawnWIconLink)
        self.setTheIcon(6, 6, self.pawnWIconLink)
        self.setTheIcon(6, 7, self.pawnWIconLink)

        for i in range(8):
            for j in range(8):
                self.chessBoard.addWidget(self.btnBoard[i][j], i, j, 1, 1)

        self.layoutWidget2 = QtWidgets.QWidget(self.mainFrame)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 6, 17, 625))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.labels1to8 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.labels1to8.setContentsMargins(0, 0, 0, 0)
        self.labels1to8.setObjectName("labels1to8")
        self.label8 = QtWidgets.QLabel(self.layoutWidget2)
        self.label8.setStyleSheet("color: white;\n"
"font-size: 28px;\n"
"height: 65px;")
        self.label8.setAlignment(QtCore.Qt.AlignCenter)
        self.label8.setObjectName("label8")
        self.labels1to8.addWidget(self.label8)
        self.label7 = QtWidgets.QLabel(self.layoutWidget2)
        self.label7.setStyleSheet("color: white;\n"
"font-size: 28px;\n"
"height: 65px;")
        self.label7.setAlignment(QtCore.Qt.AlignCenter)
        self.label7.setObjectName("label7")
        self.labels1to8.addWidget(self.label7)
        self.label6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label6.setStyleSheet("color: white;\n"
"font-size: 28px;\n"
"height: 65px;")
        self.label6.setAlignment(QtCore.Qt.AlignCenter)
        self.label6.setObjectName("label6")
        self.labels1to8.addWidget(self.label6)
        self.label5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label5.setStyleSheet("color: white;\n"
"font-size: 28px;\n"
"height: 65px;")
        self.label5.setAlignment(QtCore.Qt.AlignCenter)
        self.label5.setObjectName("label5")
        self.labels1to8.addWidget(self.label5)
        self.label4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label4.setStyleSheet("color: white;\n"
"font-size: 28px;\n"
"height: 65px;")
        self.label4.setAlignment(QtCore.Qt.AlignCenter)
        self.label4.setObjectName("label4")
        self.labels1to8.addWidget(self.label4)
        self.label3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label3.setStyleSheet("color: white;\n"
"font-size: 28px;\n"
"height: 65px;")
        self.label3.setAlignment(QtCore.Qt.AlignCenter)
        self.label3.setObjectName("label3")
        self.labels1to8.addWidget(self.label3)
        self.label2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label2.setStyleSheet("color: white;\n"
"font-size: 28px;\n"
"height: 65px;")
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setObjectName("label2")
        self.labels1to8.addWidget(self.label2)
        self.label1 = QtWidgets.QLabel(self.layoutWidget2)
        self.label1.setStyleSheet("color: white;\n"
"font-size: 28px;\n"
"height: 65px;")
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName("label1")
        self.labels1to8.addWidget(self.label1)
        self.layoutWidget3 = QtWidgets.QWidget(self.mainFrame)
        self.layoutWidget3.setGeometry(QtCore.QRect(38, 634, 645, 36))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.labelsatoh = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.labelsatoh.setContentsMargins(0, 0, 0, 0)
        self.labelsatoh.setObjectName("labelsatoh")
        self.labela = QtWidgets.QLabel(self.layoutWidget3)
        self.labela.setStyleSheet("color: white;\n"
"font-size: 28px;\n"
"height: 65px;")
        self.labela.setAlignment(QtCore.Qt.AlignCenter)
        self.labela.setObjectName("labela")
        self.labelsatoh.addWidget(self.labela)
        self.labelb = QtWidgets.QLabel(self.layoutWidget3)
        self.labelb.setStyleSheet("color: white;\n"
"font-size: 28px;\n"
"height: 65px;")
        self.labelb.setAlignment(QtCore.Qt.AlignCenter)
        self.labelb.setObjectName("labelb")
        self.labelsatoh.addWidget(self.labelb)
        self.labelc = QtWidgets.QLabel(self.layoutWidget3)
        self.labelc.setStyleSheet("color: white;\n"
"font-size: 28px;\n"
"height: 65px;")
        self.labelc.setAlignment(QtCore.Qt.AlignCenter)
        self.labelc.setObjectName("labelc")
        self.labelsatoh.addWidget(self.labelc)
        self.labeld = QtWidgets.QLabel(self.layoutWidget3)
        self.labeld.setStyleSheet("color: white;\n"
"font-size: 28px;\n"
"height: 65px;")
        self.labeld.setAlignment(QtCore.Qt.AlignCenter)
        self.labeld.setObjectName("labeld")
        self.labelsatoh.addWidget(self.labeld)
        self.labele = QtWidgets.QLabel(self.layoutWidget3)
        self.labele.setStyleSheet("color: white;\n"
"font-size: 28px;\n"
"height: 65px;")
        self.labele.setAlignment(QtCore.Qt.AlignCenter)
        self.labele.setObjectName("labele")
        self.labelsatoh.addWidget(self.labele)
        self.labelf = QtWidgets.QLabel(self.layoutWidget3)
        self.labelf.setStyleSheet("color: white;\n"
"font-size: 28px;\n"
"height: 65px;")
        self.labelf.setAlignment(QtCore.Qt.AlignCenter)
        self.labelf.setObjectName("labelf")
        self.labelsatoh.addWidget(self.labelf)
        self.labelg = QtWidgets.QLabel(self.layoutWidget3)
        self.labelg.setStyleSheet("color: white;\n"
"font-size: 28px;\n"
"height: 65px;")
        self.labelg.setAlignment(QtCore.Qt.AlignCenter)
        self.labelg.setObjectName("labelg")
        self.labelsatoh.addWidget(self.labelg)
        self.labelh = QtWidgets.QLabel(self.layoutWidget3)
        self.labelh.setStyleSheet("color: white;\n"
"font-size: 28px;\n"
"height: 65px;")
        self.labelh.setAlignment(QtCore.Qt.AlignCenter)
        self.labelh.setObjectName("labelh")
        self.labelsatoh.addWidget(self.labelh)
        Chess.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Chess)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1076, 20))
        self.menubar.setObjectName("menubar")
        Chess.setMenuBar(self.menubar)

        self.retranslateUi(Chess)
        QtCore.QMetaObject.connectSlotsByName(Chess)

    def retranslateUi(self, Chess):
        _translate = QtCore.QCoreApplication.translate
        Chess.setWindowTitle(_translate("Chess", "Chess"))
        self.botScore.setText(_translate("Chess", "0"))
        self.humanScore.setText(_translate("Chess", "0"))
        self.humanTimer.setText(_translate("Chess", "00:00"))
        self.botTimer.setText(_translate("Chess", "00:00"))
        self.botLabel.setText(_translate("Chess", "BOT"))
        self.humanLabel.setText(_translate("Chess", "HUMAN"))
        self.botScoreLabel.setText(_translate("Chess", "SCORE"))
        self.humanScoreLabel.setText(_translate("Chess", "SCORE"))
        self.botTimerLabel.setText(_translate("Chess", "TIMER"))
        self.humanTimerLabel.setText(_translate("Chess", "TIMER"))
        self.chessIconText.setText(_translate("Chess", "C H E S S"))
        self.label8.setText(_translate("Chess", "8"))
        self.label7.setText(_translate("Chess", "7"))
        self.label6.setText(_translate("Chess", "6"))
        self.label5.setText(_translate("Chess", "5"))
        self.label4.setText(_translate("Chess", "4"))
        self.label3.setText(_translate("Chess", "3"))
        self.label2.setText(_translate("Chess", "2"))
        self.label1.setText(_translate("Chess", "1"))
        self.labela.setText(_translate("Chess", "a"))
        self.labelb.setText(_translate("Chess", "b"))
        self.labelc.setText(_translate("Chess", "c"))
        self.labeld.setText(_translate("Chess", "d"))
        self.labele.setText(_translate("Chess", "e"))
        self.labelf.setText(_translate("Chess", "f"))
        self.labelg.setText(_translate("Chess", "g"))
        self.labelh.setText(_translate("Chess", "h"))

        # Adding Handler on Click to all the chess positions.
        for i in range(8):
            for j in range(8):
                self.btnBoard[i][j].clicked.connect(partial(self.makeMove, i, j))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle(QtWidgets.QStyleFactory.create('Fusion'))
    Chess = QtWidgets.QMainWindow()
    ui = Ui_Chess()
    ui.setupUi(Chess)
    Chess.show()
    sys.exit(app.exec_())
